quiz_proj/quiz_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
    # path('login/', views.LoginView.as_view(), name='login'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz_proj/quizes/urls.py
from django.contrib.auth import views
from django.urls import path

from quizes.views import (QuizListView, quiz_view, quiz_data_view,
                          save_quiz_view, user_login, main_page, sign_up, TopicQuizListView)


app_name = 'quizes'
urlpatterns = [
    path('', TopicQuizListView.as_view(), name='pages'),
    path('quize/<pk>/', QuizListView.as_view(), name='main-view'),
    path('quize/<pk>/<pk_quiz>/', quiz_view, name='quiz-view'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('quize/<pk>/save/', save_quiz_view, name='save-view'),
    path('quize/<pk>/<pk_quiz>/data/', quiz_data_view, name='quiz-data-view'),
    path('sign-up/', sign_up, name='sign-up'),
]

quiz_proj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.img' %}"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app | {% block title %}{% endblock title %}</title>
</head>
<body>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href=
                {% if request.user.is_authenticated %}
                    "{% url 'quizes:pages' %}"
                {% else %}
                    "{% url 'quizes:login' %}"
                {% endif %}
            >Головна</a>
            <div class="ml-auto" id="header">
                <span class="user text-white"> <!-- Добавлен класс text-white -->
                    {% if request.user.is_authenticated %}
                        <form id="logout-form" action="{% url 'quizes:logout' %}" method="POST" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link text-white" style="padding: 0; border: none; background: none;">Вийти</button>
                        </form>
                    {% else %}
                        <a href="{% url 'quizes:login' %}" class="text-white">Війти</a> <!-- Добавлен класс text-white -->
                    {% endif %}
                </span>
            </div>
        </nav>
    {% endblock %}

    <div class="container mt-3">
        {% block nav_content %}
        {% endblock nav_content %}
        {% block content %}
        {% endblock content %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>